import { describe, expect, it } from 'vitest';
import { claudePrintOutputSchema } from '../../../../src/adaptadores/geracao/esquemas.js';

/**
 * Unit tests for the `claude -p --output-format json` output schema (S0-T5). Synthetic fixture
 * shaped as what the PO gathered on this machine — it can't be confirmed against a real call
 * because no test in this project may touch the network (CLAUDE.md, docs/TESTES.md). See the
 * comment at the top of src/adaptadores/geracao/esquemas.ts.
 */
describe('claudePrintOutputSchema', () => {
  const validOutput = {
    type: 'result',
    subtype: 'success',
    is_error: false,
    duration_ms: 5423,
    num_turns: 1,
    result: 'understanding generated by the model',
    session_id: '11111111-2222-4333-8444-555555555555',
    total_cost_usd: 0.1532,
    usage: {
      input_tokens: 12000,
      output_tokens: 340,
      cache_creation_input_tokens: 0,
      cache_read_input_tokens: 11800,
    },
    modelUsage: {
      'claude-sonnet-5': { inputTokens: 12000, outputTokens: 340 },
    },
    permission_denials: [],
    uuid: '22222222-3333-4444-8555-666666666666',
  };

  it('accepts the full output gathered by the PO', () => {
    const result = claudePrintOutputSchema.parse(validOutput);

    expect(result.is_error).toBe(false);
    expect(result.usage.input_tokens).toBe(12000);
    expect(result.modelUsage).toStrictEqual({
      'claude-sonnet-5': { inputTokens: 12000, outputTokens: 340 },
    });
  });

  it('accepts is_error true with an error result', () => {
    const result = claudePrintOutputSchema.parse({
      ...validOutput,
      is_error: true,
      subtype: 'error_during_execution',
    });

    expect(result.is_error).toBe(true);
  });

  it('rejects output without the usage object', () => {
    const withoutUsage: Record<string, unknown> = { ...validOutput };
    delete withoutUsage['usage'];
    const result = claudePrintOutputSchema.safeParse(withoutUsage);

    expect(result.success).toBe(false);
  });

  it('rejects session_id that is not a uuid', () => {
    const result = claudePrintOutputSchema.safeParse({
      ...validOutput,
      session_id: 'not-a-uuid',
    });

    expect(result.success).toBe(false);
  });

  it('rejects usage with a negative token count', () => {
    const result = claudePrintOutputSchema.safeParse({
      ...validOutput,
      usage: { ...validOutput.usage, input_tokens: -1 },
    });

    expect(result.success).toBe(false);
  });

  it('rejects is_error that is not a boolean', () => {
    const result = claudePrintOutputSchema.safeParse({ ...validOutput, is_error: 'false' });

    expect(result.success).toBe(false);
  });
});
